---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubi-sensitive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubi-sensitive
  template:
    metadata:
      labels:
        app: ubi-sensitive
    spec:
      containers:
      - name: ubi
        image: redhat/ubi8:8.7-1037
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: DB_PASSWORD_SECRET
          value: "SECRET"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
