---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubi-hostshare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubi-hostshare
  template:
    metadata:
      labels:
        app: ubi-hostshare
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
      - name: ubi
        image: redhat/ubi8
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
