apiVersion: v1
kind: Service
metadata:
  name: ubi-lb
  labels:
    app: ubi
spec:
  ports:
    - port: 22
  selector:
    app: ubi
  type: LoadBalancer
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ubi
  labels:
    app: ubi
spec:
  selector:
    matchLabels:
      app: ubi
  template:
    metadata:
      labels:
        app: ubi
    spec:
      containers:
      - name: ubi
        image: redhat/ubi8
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 22
          name: http
          protocol: TCP
